### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by fjaguero** [juliancwirko/react-redux-webpack-meteor#4]
Hey, thanks for the amazing post and work. I also love both React and Meteor. 

I was wondering if I can use this example as a base for a small personal project that will also be on GitHub (MIT).

**Comment by juliancwirko** [comment]
Of course you can :) 
I'll add MIT license

**Comment by fjaguero** [comment]
Thanks. I've been looking your themes, so maybe I contribute that way :tada:
