### ISSUE TITLE
Would you consider updating react-hot-loader?

### ISSUE THREAD

**Issue by csillag** [juliancwirko/react-redux-webpack-meteor#6]
[Currently](https://github.com/juliancwirko/react-redux-webpack-meteor/blob/39f013655034811e403f67d4023d21f97b7c503e/react-client-app/package.json#L67), the client project uses v1.3.0 of [react-hot-loader](https://github.com/gaearon/react-hot-loader).

There are quite a [few issues](https://twitter.com/dan_abramov/status/722040946075045888) with that old version, which are fixed by the recent 3.0 beta versions. Would you please consider updating to that version? (There are examples out there about using that.)

Thanks.

**Comment by juliancwirko** [comment]
Yes, I thought about that. For sure it needs to be updated. 
I'll try to do this as soon as the version 3 come out of beta.

**Comment by csillag** [comment]
> I'll try to do this as soon as the version 3 come out of beta.

I asked about the schedule just recently: https://github.com/gaearon/react-hot-loader/pull/240#issuecomment-255593604

There is no ETA, but many are already migrating to the beta, because the errors in the old version are worse than the remaining problems with the new beta.

**Comment by juliancwirko** [comment]
Ok, so I'll get back to it soon. Thanks.

**Comment by csillag** [comment]
I asked about the schedule just recently:
https://github.com/gaearon/react-hot-loader/pull/240#issuecomment-255593604

There is no ETA, but most people are already migrating to it, because the
errors in the old version are worse than the remaining problems with the
new beta.

**Comment by juliancwirko** [comment]
Updated
